AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda_app

  Sample SAM Template for lambda_app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  UpdateElasticSearchFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: UpdateElasticSearch
      Description: Reads from dynamodb stream and updates elasticsearch with new data
      CodeUri: .
      Handler: handler.lambda_handler
      Runtime: python3.7
      # Events:
      #   HelloWorld:
      #     Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      #     Properties:
      #       Path: /hello
      #       Method: get
      Events:
        ReadDynamoDBStream:
          Type: DynamoDB
          Properties:
            Stream: arn:aws:dynamodb:ddblocal:000000000000:table/Profiles/stream/2020-08-05T04:47:37.424
            StartingPosition: TRIM_HORIZON
            BatchSize: 10



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  UpdateElasticSearchFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt UpdateElasticSearch.Arn
